version: '3'

services:
  # Configuções para o MySQL
  db-mysql:
    image: mysql:8.0    
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - 3306:3306
    networks:
      - app_network

  # Client Web para acessar o MYSQL
  adminer:
    image: adminer
    ports:
      - 8085:8080
    networks: 
      - app_network
       
networks:
  app_network:
    driver: bridge